spring.datasource.url=jdbc:postgresql://localhost:5432/support_ticket_db
spring.datasource.username=postgres
spring.datasource.password=1903

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=support-ticket-desk
server.port=5000
